### ISSUE TITLE
augustus 3.3.3 still has an error for fix_in_frame_stop_codon_genes.py

### ISSUE THREAD

**Issue by ovidp** [Gaius-Augustus/Augustus#101]
Hi. I have the same error as that reported in #82 (error fix_in_frame_stop_codon_genes.py) after waiting for 3 days for braker to finish and blocking important cluster resources. @KatharinaHoff What do we need to do to not have this error and failed augustus/braker? I am using augustus 3.3.3 which should have the fix already. 
More info at: https://github.com/Gaius-Augustus/BRAKER/issues/127
Thanks

_Originally posted by @ovidp in https://github.com/Gaius-Augustus/Augustus/issues/82#issuecomment-560454816_

**Comment by KatharinaHoff** [comment]
Did you git clone AUGUSTUS? Because we believe the error has been fixed in the latest code. (Not release download, the error is still in there.)

**Comment by ovidp** [comment]
Yes, this is correct. Cloning Augustus directly from github solves the issue. Thank you
