### ISSUE TITLE
optimize_augustus: Parallel::ForkManager not located

### ISSUE THREAD

**Issue by ckeeling** [Gaius-Augustus/Augustus#106]
I am running Augustus 3.3.3 (installed thru linuxbrew), via BUSCO, as part of a Maker annotation pipeline.  The log file suggests optimize_augustus.pl is not recognizing that Parallel::ForkManager is installed.

```
...
The perl module Parallel::ForkManager is required to run optimize_augustus.pl in parallel.
Install this module first. On Ubuntu linux install with
sudo apt-get install libparallel-forkmanager-perl
Will now run sequentially (--cpus=1)...
```

I believe Parallel::ForkManager is installed correctly, but locally, not via sudo:

```bash
perldoc -l Parallel::ForkManager
/home/ckeeling/.linuxbrew/Cellar/perl/5.30.0/lib/perl5/site_perl/5.30.0/Parallel/ForkManager.pm
```

I can evaluate the portion of optimize_augustus on the command line, and I don't get this error.

```bash
perl -e 'my $got_ForkManager = 0;
$cmdpars{'cpus'}=32;
eval { require Parallel::ForkManager };
unless ($@) {
    $got_ForkManager = 1;
    Parallel::ForkManager->import();
}
print "$got_ForkManager\t$cmdpars{'cpus'}";
if ( !$got_ForkManager && $cmdpars{'cpus'} > 1 ) {
    print STDERR
        "The perl module Parallel::ForkManager is required to run optimize_augustus.pl in parallel.\n";
    print STDERR "Install this module first. On Ubuntu linux install with\n";
    print STDERR "sudo apt-get install libparallel-forkmanager-perl\n";
    print STDERR "Will now run sequentially (--cpus=1)...\n";
    $cmdpars{'cpus'} = 1;
}
'
1	32
```

Any suggestions on how to get this working parallel?

**Comment by KatharinaHoff** [comment]
Maybe your Perl doesn’t know where to look for local libraries. There exists a PERL5LIB variable that you can extend and export, e.g. in your bashr

**Comment by ckeeling** [comment]
Thanks @KatharinaHoff Somehow I managed to comment that line out in my .bashrc at some point.  I'm surprised it didn't mess other things up earlier.
