### ISSUE TITLE
Ubuntu 18.04 version VS GitHub version

### ISSUE THREAD

**Issue by cement-head** [Gaius-Augustus/Augustus#115]
I do not understand what the following means when refering to the version of Augustus in the Ubuntu repos: "This currently installs only a single-genome version without comparative gene prediction capability:" 

What is a "single-genome version"?

And what does "without comparative gene prediction capability" mean?
TIA

**Comment by KatharinaHoff** [comment]
AUGUSTUS can predict genes in a single genome or in many aligned genomes
simultaneously. If it says it can only predict in single genome, than
that’s what it means.

Katharina

**Comment by MarioStanke** [comment]
The single-genome version predicts genes in a single genome at a time. This is what all other gene-finders do as well. 
The comparative version (AUGUSTUS-CGP, multi-genome version), predicts the genes in multiple genomes simultaneously. You need a genome-alignment for this.

**Comment by cement-head** [comment]
Okay, thanks - so if I'm running AUGUSTUS via BUSCO 4.0.4, this shouldn't make a difference - me thinks.
