### ISSUE TITLE
 mysql++.h: No such file or directory

### ISSUE THREAD

**Issue by FabianDK** [Gaius-Augustus/Augustus#121]
Hello,

I was trying to install Augustus for use with Braker2 but I am getting the error "/include/randseqaccess.hh:20:21: fatal error: mysql++.h: No such file or directory" when I type 'make'. I am working in a conda environment and have installed all dependencies before. I am also getting the error outside the environment. Could you please help resolving this?

make
> mkdir -p bin
> cd src && make
> make[1]: Entering directory `/nfs/research1/a/b/Programs/Augustus/src'
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o genbank.o genbank.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o properties.o properties.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o pp_profile.o pp_profile.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o pp_hitseq.o pp_hitseq.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o pp_scoring.o pp_scoring.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o statemodel.o statemodel.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o namgene.o namgene.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o types.o types.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o gene.o gene.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o evaluation.o evaluation.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o motif.o motif.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o geneticcode.o geneticcode.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o hints.o hints.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o extrinsicinfo.o extrinsicinfo.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o projectio.o projectio.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o intronmodel.o intronmodel.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o exonmodel.o exonmodel.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o igenicmodel.o igenicmodel.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o utrmodel.o utrmodel.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o merkmal.o merkmal.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o vitmatrix.o vitmatrix.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o lldouble.o lldouble.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o mea.o mea.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o graph.o graph.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o meaPath.o meaPath.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o exoncand.o exoncand.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> g++ -c -Wall -Wno-sign-compare -pedantic -g -ggdb -O3  -DZIPINPUT -std=c++11 -DCOMPGENEPRED -o randseqaccess.o randseqaccess.cc -I../include -I/usr/include/lpsolve -I/usr/include/mysql -I/usr/include/mysql++ 
> In file included from randseqaccess.cc:10:0:
> ../include/randseqaccess.hh:20:21: fatal error: mysql++.h: No such file or directory
>  #include <mysql++.h>
>                      ^
> compilation terminated.
> make[1]: *** [randseqaccess.o] Error 1
> make[1]: Leaving directory `/nfs/research1/a/b/Programs/Augustus/src'
> make: *** [all] Error 2
>

**Comment by starling13** [comment]
You should install mysqlc++ library from https://tangentsoft.com/mysqlpp/home

**Comment by FabianDK** [comment]
Thanks. For everyone having the same issue, here is my solution:

> cd mysql++-3.2.5
> mkdir /nfs/research1/mysql++_install
> ./configure --prefix=/nfs/research1/mysql++_install
> make
> make install
> cd Augustus/src
> nano Makefile
> #change make file in src
> INCLS   += -I/usr/include/mysql -I/nfs/research1/mysql++_install # the path to mysql++ may have to be adjusted
