### ISSUE TITLE
Recreating output from web server

### ISSUE THREAD

**Issue by droeatumn** [Gaius-Augustus/Augustus#124]
The output from the web server includes, .aa, .cdsexons, .codingseq, etc. files. Is there a way to create or reproduce these files via running stand alone?

**Comment by droeatumn** [comment]
I see it is in scripts/getAnnoFasta.pl.

**Comment by KatharinaHoff** [comment]
getAnnoFasta.pl extracts the information from AUGUSTUS gff. getAnnoFastaFromJoingenes.py extracts the information from gff and genome FASTA.
