### ISSUE TITLE
updating the apt package

### ISSUE THREAD

**Issue by droeatumn** [Gaius-Augustus/Augustus#125]
The latest GitHub release is 3.3.3. The latest apt release is 3.3. Can someone teach me how to request that the apt release be upgraded?

**Comment by MarioStanke** [comment]
The Debian package is often not the most current GitHub release. However,
it should be updated in the next few weeks.

Mario

Am So., 8. März 2020 um 14:00 Uhr schrieb Dave Roe <notifications@github.com

**Comment by droeatumn** [comment]
Thank you.
