### ISSUE TITLE
Source code of Augustus v3.2.1 still available ?

### ISSUE THREAD

**Issue by samfux84** [Gaius-Augustus/Augustus#128]
Hi,

I would like to ask if the source code of version v3.2.1 is still available for download ? The oldest version I could find in this repository is 3.3.1-tag1

Best regards

Sam

**Comment by MarioStanke** [comment]
Yes, you can download it here: http://bioinf.uni-greifswald.de/augustus/binaries/old/
According to HISTORY.TXT that is the version from October 23rd, 2015.


Best, Mario

**Comment by samfux84** [comment]
Thank you very much for the reply.
