### ISSUE TITLE
[Braker] filterGenesIn_mRNAname.pl

### ISSUE THREAD

**Issue by grexor** [Gaius-Augustus/Augustus#157]
Dear all,

I am using Braker to train Augustus with some RNA-seq data, however, this particular Perl script **filterGenesIn_mRNAname.pl** doesn't work.

It takes a GTF and a GeneBank file as input and should filter the genes in GeneBank based on the genes present in GTF. Now, I am not very familiar with Perl, but doing a short debug it seems to be completely broken, even the parsing of the GTF (transcript_id) doesn't work.

Is anyone here familiar with this script, can you check please? I can also provide input examples.

Thanks,
Gregor

**Comment by KatharinaHoff** [comment]
Have you updated AUGUSTUS scripts from github (git clone)?

Katharina

**Comment by grexor** [comment]
Good point, thanks Katharina, will check it out, Cheers, Gregor

**Comment by grexor** [comment]
I see, you fixed the regular expression Katharina in November last year, didn't check, should work now, cool! Thanks, Gregor

https://github.com/Gaius-Augustus/Augustus/commit/c21845d95a9928afa6c6ed5e7a41a4a3ada9eac2#diff-38098d448be55b5797f0f02b37024105
