### ISSUE TITLE
Create README.md from README.TXT

### ISSUE THREAD

**Issue by sherbold** [Gaius-Augustus/Augustus#16]
The README.md is better formated and gives a nive front page on github. As part of this, the contents may also be revised. 

For example, I just compiled augustus from scratch in a clean Ubuntu VM. Finding all the dependencies to install with apt-get in the readme was a bit annoying. 

I suggest to extend the readme with an apt-get statement that installs dependencies. This is also a precursor for an automated deployment of augustus, as well as for CI with Travis. 

Please use this issue for discussing all further changes that should be made, we can close this issue once we are satisfied with the new README.

**Comment by KatharinaHoff** [comment]
Hi Mario, 
the species that AUGUSTUS has been trained for are listed in the README files, twice: once as "AUGUSTUS has been trained for"... and once as "this identifier corresponds to that species".  
a) could we collapse that into one instead two locations (i.e. refer to the table in the introduction)
b) should we even still mention the species in the md file since the handling of species names will be changed, soon?
Katharina

**Comment by MarioStanke** [comment]
Steffen and Katharina,

great, Steffen. I agree. With Katharina, too. As the species are put in a
repository, the list of species will have to be compiled automatically from
a command. I suggest to leave it until that has happened, so it is changed
only once.



2018-09-13 14:06 GMT+02:00 Katharina Hoff <notifications@github.com>:

**Comment by sherbold** [comment]
We should update the README to include a tutorial on building the docker container and running Augustus from there.

As a side effect, I collected all required depencies for building on Ubuntu 18.04 in the Dockerfile, which we could make into a single apt-get statements that installs everything, the we add to the README.

**Comment by sherbold** [comment]
The new Readme looks good for me. I made a minor change regarding Docker, because the repository url is not hard-coded in the Dockerfile anymore. 

All that remains to be done (for now) is add a description for using Augustus with Windows, right?
