### ISSUE TITLE
Does augustus have mutlithread option ? 

### ISSUE THREAD

**Issue by StromTroopers** [Gaius-Augustus/Augustus#161]
Hello, I checked on the doc and I did not see any option in order to set the desired number of cpu for a run, does it exists?

Does Augustus run only in 1 cpu / run or does it take all the cpu available on the machine ? 

Thank you for you answer.

**Comment by MarioStanke** [comment]
No, it does not and uses only one thread. We achieve parallelism by
splitting the input.

This book chapter gives the command lines:
https://math-inf.uni-greifswald.de/storages/uni-greifswald/fakultaet/mnf/mathinf/stanke/augustus_wrp.pdf

The relevant scripts are
createAugustusJoblist.pl and
join_aug_pred.pl


Am Di., 30. Juni 2020 um 14:01 Uhr schrieb Grendek <notifications@github.com

**Comment by StromTroopers** [comment]
Ok I see thank you for yout time

**Comment by StromTroopers** [comment]
Ok I see thank you for yout time
