### ISSUE TITLE
extrinsic.MPE.cfg does not work with --softmasking=1 (default)

### ISSUE THREAD

**Issue by MarioStanke** [Gaius-Augustus/Augustus#165]
augustus --species=human --hintsfile=../examples/hints.gff --extrinsicCfgFile=../config/extrinsic/extrinsic.MPE.cfg ../examples/example.fa

augustus: ERROR
    When the softmasking option is turned on, the source RM must be specified in the extrinsic config file.

**Comment by esolares** [comment]
Hi,

I am getting this error now. What should I do to work around this or fix it?

**Comment by dongzhang0725** [comment]
Hi @MarioStanke ,

I encountered the same problem and have no idea, have you resolved it?

**Comment by schellt** [comment]
Hi @MarioStanke,
I am running `autoAug.pl` from Augustus 3.4.0 and have the same issue.
I started `autoAug.pl` like this:
```
autoAug.pl \
	--species=my_species \
	--genome=my_assembly.fa.masked \
	--cdna=my_cdna.fasta \
	--cpus=96 \
	-v -v -v \
	--pasa \
	--useGMAPforPASA \
	--noninteractive
```
I adapted the `--noninteractive` option for our system and it was running before.
Now, when prediction with hints starts, there comes this error:
```
$ augustus --species=my_species --UTR=off --hintsfile=../../hints/hints.gff --extrinsicCfgFile=${AUGUSTUS_CONFIG_PATH}/extrinsic/extrinsic.E.cfg --exonnames=on  --AUGUSTUS_CONFIG_PATH=${AUGUSTUS_CONFIG_PATH} ${OUT}/augustus/autoAug/seq/split/genome_clean.split.1.fa > ${OUT}/autoAug/autoAugPred_hints/shells/aug1.out
When the softmasking option is turned on, the source RM must be specified in the extrinsic config file.

Could not read in file with the configuration of hints: ${AUGUSTUS_CONFIG_PATH}/extrinsic/extrinsic.E.cfg

augustus: ERROR
	When the softmasking option is turned on, the source RM must be specified in the extrinsic config file.



```
Before starting the prediction with hints `autoAug.pl` automatically chooses the default hint configuration, which is not working:
```
[...]
1 ####### Now predicting genes with hints in the whole sequence...#######
2 "perl autoAugPred.pl -g=${OUT}/autoAug/seq/genome_clean.fa --species=my_species --hints=${OUT}/autoAug/hints/hints.E.gff  --noninteractive --cname=fe -w=${OUT}/autoAug -v -v -v  --cpus=96" ...

3 Created directory ${OUT}/autoAug/autoAugPred_hints.
3 All necessary directories have been created under ${OUT}/autoAug/autoAugPred_hints
```
**`2 Using default hint configuration file extrinsiccfg=${AUGUSTUS_CONFIG_PATH}/extrinsic/extrinsic.E.cfg`**
```
2 Using existing split genome FASTA files.
[...]
```
When I use e.g. the config file `extrinsic.M.RM.E.W.cfg` instead, it works.
I would expect that `autoAug.pl` chooses the appropriate config file given the settings.
A quick and dirty solution would be to copy `extrinsic.M.RM.E.W.cfg` to `extrinsic.E.cfg` but I am not sure, if this is OK even when it runs without errors.
It would be nice, if you could have look at this and some advice.
Thanks a lot in advance.
Best,
Tilman
