### ISSUE TITLE
update bam2wig README and Makefile

### ISSUE THREAD

**Issue by AGI-admin** [Gaius-Augustus/Augustus#17]
The instructions for compiling bam2wig (https://github.com/Gaius-Augustus/Augustus/blob/master/auxprogs/bam2wig/README.txt) are outdated and should be updated, as described here, https://github.com/samtools/tabix/issues/24
Basically, the repo for tabix is not maintained any longer, and installation of htslib will provide the installation of tabix.  https://github.com/Gaius-Augustus/Augustus/blob/c23440b630a1af0b7c908cedc6e2d6e0e063c2a9/auxprogs/bam2wig/Makefile#L21  could be updated to `TABIX=$(TOOLDIR)/htslib/`or just removed since it is already defined with `HTSLIB`

**Comment by hmehlan** [comment]
resolved #25
