### ISSUE TITLE
executable can't be found

### ISSUE THREAD

**Issue by cement-head** [Gaius-Augustus/Augustus#171]
```
$ autoAug.pl -g xtgenome.fna --species=xtropicalis -c rna.fna -v -v --pasa --useexisting
Option c is ambiguous (cdna, cname)
2 checking for installed programs ... Error: augustus executable not found at /home/cbfgws3/augustus/config/../bin/augustus.
```
Where is the executable?

**Comment by MarioStanke** [comment]
There should be an executable file
/home/cbfgws3/augustus/bin/augustus

If not, the problem might be that you haven't built (compiled) it with
"make" in /home/cbfgws3/augustus.

Am Fr., 31. Juli 2020 um 23:28 Uhr schrieb Andor J Kiss <
notifications@github.com>:

**Comment by cement-head** [comment]
Yeah, okay - thanks - somehow the $PATH got messed up, I fixed that and it works.
