### ISSUE TITLE
GFF file from Genbank?

### ISSUE THREAD

**Issue by cement-head** [Gaius-Augustus/Augustus#174]
For the autoAug.pl training file, should I use the GFF file from GenBank for a well annotated organism?  Such as Xenopus tropicalis?  Based on what I've read, the answer would seem to be "no", as this GFF file would contain WAY too many genes and basically clog up the whole process.

So, I should re-train Augustus using the cDNA file and the gDNA file?  Generating a GFF file via PASA, which can then used to retrain Augustus.  Am I correct in this reasoning?

**Comment by cement-head** [comment]
Does anyone who's performed this retraining have some suggestions?  Thanks!

**Comment by KatharinaHoff** [comment]
Download the protein fasta file from the FTP server. You can feed that with
a genome file into either autoAug.pl or BRAKER with GenomeThreader. Don’t
forget to simply FASTA headers beforehand. (BRAKER will be a lot faster.)

**Comment by cement-head** [comment]
Okay - what do you mean by "simplify the FASTA headers"?

**Comment by KatharinaHoff** [comment]
The FASTA headers in NCBI FASTA files are long and complex. For running
genome annotation pipelines, it usually helps to prevent problems with
FASTA headers if you simplify the headers, i.e. make them short, unique and
very simple. Example: ">seq1" is a simple header.
https://github.com/Gaius-Augustus/Augustus/blob/master/scripts/simplifyFastaHeaders.pl

**Comment by cement-head** [comment]
Thanks!

**Comment by cement-head** [comment]
Hmm....
I get this on Ubuntu 18.04:
$ autoAug.pl -g xt_gdna.fna -t protein_namefix.faa --species=xtropicalis --cdna=rna-namefix.faa --verbose=3
Option verbose does not take an argument
2 checking for installed programs ... Error: augustus executable not found at /usr/share/augustus/config/../bin/augustus.
