### ISSUE TITLE
Setting AUGUSTUS path variable properly

### ISSUE THREAD

**Issue by cement-head** [Gaius-Augustus/Augustus#176]
Using Ubuntu 18.04 LTS.  Installed Augustus 3.3 from the package manager.

I'm getting this error while attempting to run <autoAug.pl> script: 

```
$ autoAug.pl -g xt_gdna.fna -t protein_namefix.faa --species=xtropicalis --cdna=rna-namefix.faa -v -v -v
2 checking for installed programs ... Error: augustus executable not found at /usr/share/augustus/config/../bin/augustus.
```

I've added these two lines into my <.bashrc> file:

```
# AUGUSTUS
export AUGUSTUS_CONFIG_PATH=/usr/share/augustus/config
export PATH=/usr/share/augustus/scripts:/usr/bin/augustus:$PATH
```
If I check my current $PATH variable, it looks to me as if the **augustus** executable is in the $PATH (at </usr/bin/augustus>)

```
$ echo $PATH
/home/cbfgws6/Programs/fasta-36.3.8g/bin/:/home/cbfgws6/Programs/blat/:/usr/share/augustus/scripts:/usr/bin/augustus:/usr/local/cuda-11.0/bin:/opt/nvidia/nsight-compute/2020.1.1:/opt/nvidia/nsight-systems/2020.3.2:/home/cbfgws6/Programs/fasta-36.3.8g/bin/:/home/cbfgws6/Programs/blat/:/usr/share/augustus/scripts**:/usr/bin/augustus**:/usr/local/cuda-11.0/bin:/opt/nvidia/nsight-compute/2020.1.1:/opt/nvidia/nsight-systems/2020.3.2:/home/cbfgws6/Programs/fasta-36.3.8g/bin/:/home/cbfgws6/Programs/blat/:/usr/local/cuda-11.0/bin:/opt/nvidia/nsight-compute/2020.1.1:/opt/nvidia/nsight-systems/2020.3.2:/home/cbfgws6/Programs/fasta-36.3.8g/bin/:/home/cbfgws6/Programs/blat/:/usr/local/cuda-11.0/bin:/opt/nvidia/nsight-compute/2020.1.1:/opt/nvidia/nsight-systems/2020.3.2:/home/cbfgws6/Programs/fasta-36.3.8g/bin/:/home/cbfgws6/Programs/blat/:/usr/local/cuda-11.0/bin:/opt/nvidia/nsight-compute/2020.1.1:/opt/nvidia/nsight-systems/2020.3.2:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/Supermicro/SuperDoctor5$:/home/cbfgws6/Programs/blast/ncbi-blast-2.2.28+-src/c++/GCC480-Debug64/bin:/usr/share/augustus/scripts:/usr/bin$$$:/home/cbfgws6/Programs/blast/ncbi-blast-2.2.28+-src/c++/GCC480-Debug64/bin:/usr/share/augustus/scripts:/usr/bin/augustus$$$:/home/cbfgws6/Programs/blast/ncbi-blast-2.2.28+-src/c++/GCC480-Debug64/bin:/usr/share/augustus/scripts:**/usr/bin/augustus**$$$:/home/cbfgws6/Programs/blast/ncbi-blast-2.2.28+-src/c++/GCC480-Debug64/bin$$$:/home/cbfgws6/Programs/blast/ncbi-blast-2.2.28+-src/c++/GCC480-Debug64/bin$$
```

So...what is wrong?  Have I made a mistake in the $PATH, in <./bashrc>?

TIA

**Comment by MarioStanke** [comment]
The script seems to expect that the parameters (config) and the augustus executable are in sister directories. The Debian package has separated them, though.
Our fix could be to have autoAug.pl look in the PATH if it does not find the binary at the first location. As a quick fix you could
```
sudo mkdir /usr/share/augustus/bin
sudo ln -s /usr/bin/augustus /usr/share/augustus/bin
```
I the mid-term future, the parameters will not be packaged but downloaded from an online repository.

**Comment by cement-head** [comment]
Okay!  Thanks - I was starting to think that the package manager (or packing for a deb) had scrambled the set-up.  My next step was to download manually and install under my home directory.  Cheers!

**Comment by cement-head** [comment]
Well, next problem.  BLAT is installed, but only runs when I am in the BLAT directory and type:

`./blat` 

into a terminal...what's the solution?

**Comment by KatharinaHoff** [comment]
Have you added BLAT to your PATH variable?

**Comment by cement-head** [comment]
I think so...

```
$ echo $PATH
/usr/share/augustus/scripts:/usr/bin/augustus:/usr/local/cuda-11.0/bin:/opt/nvidia/nsight-compute/2020.1.1:/opt/nvidia/nsight-systems/2020.3.2:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/opt/Supermicro/SuperDoctor5$:/home/cbfgws6/Programs/blast/ncbi-blast-2.2.28+-src/c++/GCC480-Debug64/bin:/home/cbfgws6/Programs/blat/blat:/home/cbfgws6/Programs/fasta-36.3.8g/bin
```
and in my <.bashrc> (both <blat> and <pslCDnaFilter> are in the same directory)

```
# BLAT and pslCDnaFilter
export PATH=$PATH:$HOME/Programs/blat/blat
```

I can run blat, if I navigate to **/home/Programs/blat** directory and type this in the terminal:

`$ ./blat`

**Comment by cement-head** [comment]
Also, they are executable - I've check that.

**Comment by cement-head** [comment]
Nevermind, seems to work now.  Somedays..........   :-0

**Comment by hmehlan** [comment]
if ~/Programs/blat/blat is your executable blat program - does it help to set PATH in <.bashrc> to 
`export PATH=$PATH:$HOME/Programs/blat`
