### ISSUE TITLE
settings for plant genome

### ISSUE THREAD

**Issue by mictadlo** [Gaius-Augustus/Augustus#178]
Hi, 
We have a plant genome and would like to create an annotation with Augustus. However, I am not sure about the following few parameters.

- noInFrameStop=false
- allow_hinted_splicesites=atac
- genemodel=partial or --genemodel=complete
- Which settings are appropriate for a plant genome?

Thank you in advance

Michal

**Comment by MarioStanke** [comment]
I recommend to leave `genemodel` at the default (partial) for almost all application cases. You don't need to specify it.  It may be of use, say, if you want to annotate a specific region only from which you know that it does not truncate a gene.

What splice site patterns occur, depends on the species, and you might find out with spliced alignments of RNA-Seq.
If unsure, I would do
`allow_hinted_splicesite=atac`
The main ones gtag and gcag are included by default, atac is usually very rare.

`noInFrameStop=false` makes a GenBank submission easier but may decrease sensitivity, as transcripts with an in-frame stop codon are merely not reported. In-frame stops can only occur whey are spliced and span two exons. The BRAKER pipeline has now a procedure to fix these regions with another option that does not produce in-frame-stops.

**Comment by mictadlo** [comment]
Thank you.

**Comment by mictadlo** [comment]
@MarioStanke Just double cheching does `noInFrameStop=false` or `noInFrameStop=true` may decrease sensitivity, as transcripts with an in-frame stop codon are merely not reported?

**Comment by MarioStanke** [comment]
Yes, that is correct.

Am Mi., 19. Aug. 2020 um 02:50 Uhr schrieb Michał T. Lorenc <
notifications@github.com>:

**Comment by mictadlo** [comment]
Thank you, but which one `noInFrameStop=false` or `noInFrameStop=true`?
