### ISSUE TITLE
Multithread autoAug.pl process?

### ISSUE THREAD

**Issue by cement-head** [Gaius-Augustus/Augustus#181]
Is it possible to multi-thread the autoAug.pl training process on a non-GRID system, for example on a machine that has 124 threads?

How long does this take to train a new species? a few days? a week?

TIA

**Comment by KatharinaHoff** [comment]
No, it will rely on SGE. (We are not using it with SGE anymore, though...
we always execute on a single CPU.) Runtime depends a lot on the properties
of input data. It may be a day or 3-4 weeks, in extreme cases even longer.
It's not the training of AUGUSTUS that takes so long, it's the training
gene generation. Particularly Scipio has sometimes extremely large
runtimes, e.g. if proteins are mapped against repeats...

Best,
Katharina

**Comment by cement-head** [comment]
Okay, thanks.
