### ISSUE TITLE
etraining aborted

### ISSUE THREAD

**Issue by hmehlan** [Gaius-Augustus/Augustus#185]
`etraining --species=fly test.gb`
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

file "test.gb" is in this here: [test.zip](https://github.com/Gaius-Augustus/Augustus/files/5108150/test.zip)

`# augustus --version`
AUGUSTUS (3.3.3)

**Comment by hmehlan** [comment]
`$ etraining --species=fly test.malloc.gb`
...
etraining: malloc.c:2401: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted (core dumped)


`$ etraining --species=fly test.corrupted_size.gb`
...
corrupted size vs. prev_size
Aborted (core dumped)

[test.corrupted_size.gb.gz](https://github.com/Gaius-Augustus/Augustus/files/5117036/test.corrupted_size.gb.gz)
[test.malloc.gb.gz](https://github.com/Gaius-Augustus/Augustus/files/5117037/test.malloc.gb.gz)

**Comment by MarioStanke** [comment]
A funny issue that occurred when a Genbank formatted sequence was shorter than its name.

This issue and another memory error are now fixed in master:
     - genbank seqname got space reserved for sequence
       1) mostly a big waste of memory
       2) crashed in rare cases where a sequence was shorter than its name
     - r = new char[] was mismatched by delete r

**Comment by hmehlan** [comment]
running augustus with a GenBank file containing two genes
`augustus --species=fly test_strand_ok.gb`
is ok, 
but with inverse order of genes, with the one on the backward strand first, will fail:
`augustus --species=fly test_strand_segfault.gb`
`...`
`Segmentation fault (core dumped)`

(It will even fail with just the gene on the backward strand.)


[test_strand.tar.gz](https://github.com/Gaius-Augustus/Augustus/files/5174454/test_strand.tar.gz)

**Comment by MarioStanke** [comment]
The input file had the wrong syntax:
```
     source          complement(1..963)
```
This should rather be
```
     source          1..963
```
I changed it so that an error message is displayed and the .gb entry ignored.
