### ISSUE TITLE
Evidence for and against this transcript

### ISSUE THREAD

**Issue by rmwaterhouse** [Gaius-Augustus/Augustus#191]
Does anyone know of a way to stop printing 'evidence' info after the protein sequence in the output?

`# Evidence for and against this transcript:`
`# % of transcript supported by hints (any source): 0`
`# CDS exons: 0/8`
`# CDS introns: 0/7`
`# 5'UTR exons and introns: 0/1`
`# 3'UTR exons and introns: 0/0`
`# hint groups fully obeyed: 0`
`# incompatible hint groups: 0`

**Comment by MarioStanke** [comment]
This is printed whenever extrinsic evidence is available. From the top of
my head I don't know whether softmasking (=nonexonpart hints) count as
extrinsic evidence.
Do you input a hints file?
Regardless, I can introduce a program parameter for this later.

Am Do., 3. Sept. 2020 um 18:12 Uhr schrieb Rob Waterhouse <
notifications@github.com>:

**Comment by rmwaterhouse** [comment]
Thanks Mario. That's exactly why I found it strange, I'm using protein profiles not hints, and I expected such 'evidence' info to only be relevant for hints not profiles, so I was wondering if I could turn off printing this info.

**Comment by KatharinaHoff** [comment]
Please do not generally turn it off for protein profiles, @Mario Stanke
<mario.stanke@gmail.com> . I use this information for filtering
BUSCO-profile predictions (the profile supported genes are mixed with ab
initio gene models).

An option for disabling this would be cool.

**Comment by rmwaterhouse** [comment]
Update: it seems that passing softmasking=0 (with profile, not hints, predictions) makes the 'evidence' info go away.

**Comment by MarioStanke** [comment]
I am working on it here: https://github.com/Gaius-Augustus/Augustus/issues/193

**Comment by MarioStanke** [comment]
It is fixed: --printEvidence=0
