### ISSUE TITLE
Any way to compile Augustus 3.3.4 without root privileges? 

### ISSUE THREAD

**Issue by apredeus** [Gaius-Augustus/Augustus#197]
Hello, 

I'm trying to get the latest Braker2 working, which seems to require the newest Augustus. Compiling it requires lots of libraries that are absent on our cluster. For the same reason, I can't use Docker (needs root). 

Is there anything that could be done here? If not, I'll use the older version of Braker2. Would of course appreciate a conda recipe, if anybody has the time to make it. 

Thank you!

**Comment by tomasbruna** [comment]
Hello @apredeus,

the latest BRAKER2 should work well if you use the older AUGUSTUS binary and update the scripts in the [scripts folder](https://github.com/Gaius-Augustus/Augustus/tree/master/scripts).

Best,
Tomas

**Comment by apredeus** [comment]
Thank you very much! I will give it a try.
