### ISSUE TITLE
after etraining, i got zero sensitivity in tee file

### ISSUE THREAD

**Issue by chiu-shenpo** [Gaius-Augustus/Augustus#225]
**{augustus --species=bug adjust_500.test | tee firsttest.out}**
The adjust_500.test is gene_bank format after using gff2gbSmallDNA.pl and randomSplit.pl. 
Then i used etraining training new species "bug" by **{etraining --species=bug genes.gb.train}**. 
Then i run **{augustus --species=bug adjust_500.test | tee firsttest.out}** and i got zero sensitivity and theres no single predicted gene.
But i tried to use another built-in species Tetrahymena and got many predicted genes.**{augustus --species=tetrahymena adjust_500.test | tee firsttest.out}**
Can anyone tell me why i got zero sensitivity of my --species=bug?????

**Comment by MarioStanke** [comment]
I can't say. What is the output of `etraining`?
If you think this is an issue with the software then please create an example to reproduce it.

**Comment by chiu-shenpo** [comment]
> I can't say. What is the output of `etraining`?
> If you think this is an issue with the software then please create an example to reproduce it.

I dont think its software's issue. I might have an idea which is my gff file produced by PASA only noted cdna_match not cds. Unfortunately, i used this wrong cdna_match gff file turned into gene_bank.
(gff file provided by Augustus shows cds in gff instead of cdna_match)
Any idea how to create gff that contains cds not cdna_match?????

**Comment by MarioStanke** [comment]
`cdna_match` probably marks an aligned region, `cds` is a coding exon. There is a principal difference between the two as the concatenation of aligned regions is rarely a consistent gene structure.
You can have a look at BRAKER or http://bioinf.uni-greifswald.de/webaugustus/ to perform training or to construct a training set.
