### ISSUE TITLE
how can I get the 3.3.4 version

### ISSUE THREAD

**Issue by mengxin-mx-cpu** [Gaius-Augustus/Augustus#226]
how can I get the 3.3.4 version,I git clone https://github.com/Gaius-Augustus/Augustus.git,but after installing it,the version is 3.3.3, but the latest release of AUGUSTUS (v3.3.3) is not compatible with BRAKER。

(braker2) [root@node01 example]# git clone git@github.com:Gaius-Augustus/Augustus.git
Cloning into 'Augustus'...
ssh: Could not resolve hostname github.com: Name or service not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
(braker2) [root@node01 example]#

**Comment by cdeai** [comment]
I am also having problems getting BRAKER2 to work and I was wondering if it might be possible to make the stable releases of Augustus and BRAKER2 intercompatible. Or perhaps clearly state, which releases are compatible. With so many dependencies it is a struggle to get everything to work as it is, let alone having to compile both pieces of software.

Please do not get me wrong - Augustus is a great piece of software and I am very grateful for all the work you put in it, but it was never simple to train it and the introduction of BRAKER somehow made that task even more daunting.

**Comment by MarioStanke** [comment]
We made an augustus release 3.4 that should be compatible with the current BRAKER2.
