### ISSUE TITLE
Compiling on non-debian system is difficult

### ISSUE THREAD

**Issue by KatharinaHoff** [Gaius-Augustus/Augustus#261]
If you are on an HPC resource without root privileges, it is currently rather annoying to compile Augustus because you have to edit the Makefile to include boost (that you manually compiled in your home directory).

Error message:

```
In file included from ../include/genbank.hh:12,
                 from genbank.cc:10:
../include/types.hh:16:10: fatal error: boost/archive/text_oarchive.hpp: No such file or directory
 #include <boost/archive/text_oarchive.hpp>
```

Fix:

Edit the Augustus/src/Makefile to include the following:

```
ifeq (,$(findstring $(ZIPINPUT),0 false False FALSE))  # if ZIPINPUT is not defined or is something else than 0, false, False or FALSE
        CPPFLAGS += -DZIPINPUT
        LIBS    += -L${HOME}/your/boost_1_75_0/stage/lib
endif

INCLS   += -I../include -I${HOME}/your/boost_1_75_0
```
I am posting this here for the record. One of our collaboration partners who is rather experienced in compiling software recently told me he was unable to compile Augustus on his cluster due to the changes in Makefile.

**Comment by tomasbruna** [comment]
Thank you, this is useful!

It seems that a similar change needs to be done at one more location:

```
ifeq (,$(findstring $(TESTING),0 false False FALSE))  # if TESTING is not defined or is something else than 0, false, False or FALSE
    CPPFLAGS += -DTESTING
    LIBS    += -L${HOME}/your/boost_1_75_0/stage/lib
endif
```

and then everything boost-related works.

**Comment by KatharinaHoff** [comment]
Thank you, @tomasbruna . Exactly, that other modification is also required.

If you don't need CGP, it's usually ok to disable zlib and compred in the common.mk file. That makes compilation a lot easier.

**Comment by paulmenzel** [comment]
Shouldn’t you be able to set the variable `LIBS` on the command line?

    make LIBS=-L${HOME}/your/boost_1_75_0/stage/lib

**Comment by paulmenzel** [comment]
Actually, the search path is specified in `LDFLAGS`:

    make LDFLAGS="-L${HOME}/your/boost_1_75_0/stage/lib"
