### ISSUE TITLE
gff2gbSmallDNA.pl input for max-size-of-gene-flanking-DNA

### ISSUE THREAD

**Issue by Lamm-a** [Gaius-Augustus/Augustus#268]
I am wanting to turn the Augustus `gff `file into a `gbk `file but i unsure what I should populate the `max-size-of-gene-flanking-DNA` parameter with.

Any advice would be appreciated.

**Comment by tomasbruna** [comment]
The parameter specifies how much DNA is included around genes. The value `0` is fine if you want the output to contain only sequences of coding genes.

If you want to use this file for the training of AUGUSTUS somehow, the recommended value is given in the `braker.log`.

**Comment by Lamm-a** [comment]
Excellent thank you :)
