### ISSUE TITLE
homGeneMapping: `undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'` building from top directory

### ISSUE THREAD

**Issue by paulmenzel** [Gaius-Augustus/Augustus#276]
Using GNU Bash 4.3.46, GNU Make 4.3, and v3.3.1-tag1-941-g47189535, setting `CXXFLAGS` results in the build error below.

```
auxprogs/homGeneMapping/src$ make CXXFLAGS=""
g++  -DBOOST -DM_SQLITE  -o homGeneMapping main.cc gene.o genome.o sqliteDB.o -I../include -lsqlite3 
/usr/lib/gcc/x86_64-pc-linux-gnu/7.5.0/../../../../x86_64-pc-linux-gnu/bin/ld: /scratch/local/ccmlk3UJ.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/lib/gcc/x86_64-pc-linux-gnu/7.5.0/../../../../x86_64-pc-linux-gnu/bin/ld: /lib/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:46: homGeneMapping] Error 1
```

The reason is, that `-pthread` is missing. For some reason, the `CXXFLAGS` assignment in hemGeneMapping’s Makefile is ignored.

https://github.com/Gaius-Augustus/Augustus/blob/47189535180344e8aa49731237f35ce30efa8395/auxprogs/homGeneMapping/src/Makefile#L20

Building without setting `CXXFLAGS`, the assignment works.

    auxprogs/homGeneMapping/src$ make
    g++ -Wall -Wno-sign-compare -ansi -pedantic -std=c++0x -pthread -O2 -DBOOST -DM_SQLITE  -o homGeneMapping main.cc gene.o genome.o sqliteDB.o -I../include -lsqlite3 
    mkdir -p ../../../bin/
    cp homGeneMapping ../../../bin/homGeneMapping

No idea, what is going on.

**Comment by chipzz** [comment]
This is the issue:
make CXXFLAGS=""
Try this instead:
CXXFLAGS="" make

**Comment by paulmenzel** [comment]
Indeed. It’s also explained in the [GNU Make manual](https://www.gnu.org/software/make/manual/html_node/Overriding.html):

> An argument that contains ‘=’ specifies the value of a variable: ‘v=x’ sets the value of the variable v to x. If you specify a value in this way, all ordinary assignments of the same variable in the makefile are ignored; we say they have been overridden by the command line argument.
