### ISSUE TITLE
Species name

### ISSUE THREAD

**Issue by OnlineArts** [Gaius-Augustus/Augustus#285]
Hi, this is not a real issue but since I had to go through every HMM Augustus model I found some typos or outdated(changed) species names. Here we go:
Argopecten_irridians -> Argopecten irradians
candida_guilliermondii -> Meyerozyma guilliermondii
Chrysaora_chesapeakeij -> Chrysaora chesapeakei
Raphidocelis_subcapita -> Raphidocelis subcapitata
pichia_stipitis	-> Scheffersomyces stipitis

May you consider renaming some of them.

Best wishes,
Roman

**Comment by MarioStanke** [comment]
Thanks. @hmehlan , can you please check and consider this?
Roman, we are currently creating a formal structure for the species data and an online repository.
You corrections are appreciated.

**Comment by OnlineArts** [comment]
@MarioStanke 
That's good to know, maybe this helps you. It's a [JSON file derived from my code](https://gitlab.com/mosga/mosga/-/blob/v200/gui/gui-rules.json) that contains the Augustus model directory name as a key with the NCBI Taxonomy ID and the scientific name as values.

We are currently implementing a feature that performs a taxonomical tree search to identify the best suitable model for a given species (NCBI id). That could be something for you.

[augustus_models.txt](https://github.com/Gaius-Augustus/Augustus/files/6357646/augustus_models.txt)

**Comment by MarioStanke** [comment]
That looks great, also your MOSGA project.
@hmehlan is currently developing the same: A search of the taxonomy with the ETE Toolkit that will return a list of the closest relatives in the set of species for which augustus has parameters. We will also produce a tree image and provide functions to download parameters on request and to commit new parameter sets to our server. In the future, the distribution will only hold a few parameter directories, the rest is downloaded when needed.
So the development appears to be quite parallel and I suggest we coordinate.

**Comment by OnlineArts** [comment]
@MarioStanke 
Thank you very much.

Indeed, we have simultaneously [implemented](https://gitlab.com/mosga/mosga/-/commit/6501b4ab399421d45aa1423fa6df3500b1a2e31d) the same function. Although we are focused on different topics, we still have an inevitable overlap. We should coordinate or even complement ourselves. I see the potential for synergy effects.
