### ISSUE TITLE
Hanging run

### ISSUE THREAD

**Issue by berkelem** [Gaius-Augustus/Augustus#291]
Hello, 

We have received a number of reports of hanging augustus jobs from BUSCO users (see here for example: https://gitlab.com/ezlab/busco/-/issues/407). We have finally been able to replicate the problem and we have ruled out an issue with the BUSCO code. Could you please try running the following (with the attached files) and see if you can replicate and diagnose the hanging behaviour? I first noticed it on v3.3.2 but I have tested it on v3.3.3 and v3.4 and observe the same problem.

`augustus --codingseq=1 --proteinprofile=7883at4069.prfl --predictionStart=7083099 --predictionEnd=7186929 --species=tomato scaffold_540.temp`

[files.tar.gz](https://github.com/Gaius-Augustus/Augustus/files/6465474/files.tar.gz)

**Comment by MarioStanke** [comment]
It runs through on my laptop with the current version (commit hash f748db4):

```bash
/usr/bin/time -v augustus --codingseq=1 --proteinprofile=7883at4069.prfl --predictionStart=7083099 --predictionEnd=7186929 --species=tomato scaffold_540.temp > scaffold_540.gff

User time (seconds): 67.12
Maximum resident set size (kbytes): 825152
```
The job needs about 800M RAM.
Here is the result: scaffold_540.gff


Do  you have the impression that it is random behavior (inconsistent between machines)?
[scaffold_540.gff.txt](https://github.com/Gaius-Augustus/Augustus/files/6503144/scaffold_540.gff.txt)

**Comment by berkelem** [comment]
That’s interesting - I tried it on another machine and it worked as you described.
I’ll do a bit more testing to try and get to the root cause of the hanging that is being reported by users. This example clearly isn’t a true replication of the problem.
Thanks for your reply.



On 18 May 2021, at 19:23, Mario Stanke ***@***.******@***.***>> wrote:



It runs through on my laptop with the current version (commit hash f748db4<https://github.com/Gaius-Augustus/Augustus/commit/f748db476f2de1e75aaf9324f80c76aa484effe8>):

/usr/bin/time -v augustus --codingseq=1 --proteinprofile=7883at4069.prfl --predictionStart=7083099 --predictionEnd=7186929 --species=tomato scaffold_540.temp > scaffold_540.gff

User time (seconds): 67.12
Maximum resident set size (kbytes): 825152

The job needs about 800M RAM.
Here is the result: scaffold_540.gff

Do you have the impression that it is random behavior (inconsistent between machines)?
scaffold_540.gff.txt<https://github.com/Gaius-Augustus/Augustus/files/6503144/scaffold_540.gff.txt>

**Comment by berkelem** [comment]
Just an update - the problem wasn't actually with Augustus but with our logging system. We have managed to fix it now.
Thanks
