### ISSUE TITLE
Missing compute_accuracies.sh while using --eval in BRAKER2

### ISSUE THREAD

**Issue by inspirewind** [Gaius-Augustus/Augustus#299]
Hi, I want to compare annotation accuracy with the method in VARUS's Supplementary Materials,

it was
`braker.pl --genome=genome.fa --hints=hints.introns --softmasking --cores=8 --eval=annot_by_GenomeTools.fixed.gtf`

When I run the pipeline, the errors said:

`ERROR: in file /public/home/miniconda3/envs/gene_pre/bin/./helpMod.pm at line 307
 found neither 
 /public/home/yaohuipeng/soft/miniconda3/envs/gene_pre/bin/compute_accuracies.sh nor 
 /public/home/yaohuipeng/soft/miniconda3/envs/gene_pre/scripts/compute_accuracies.sh nor 
 /public/home/yaohuipeng/soft/miniconda3/envs/gene_pre/scripts/compute_accuracies.sh nor 
 /public/home/yaohuipeng/soft/miniconda3/envs/gene_pre/bin/compute_accuracies.sh!
Please Check the environment variables AUGUSTUS_CONFIG_PATH and command line options AUGUSTUS_BIN_PATH and AUGUSTUS_SCRIPTS_PATH or install AUGUSTUS, again!`

So how can I find the shell file and use it in accuracy comparison？Thanks！

**Comment by KatharinaHoff** [comment]
Please update your BRAKER from github. It’s there.
