### ISSUE TITLE
Augustus not executable - libboost issue? 

### ISSUE THREAD

**Issue by SheepwormJM** [Gaius-Augustus/Augustus#302]
Hi,

I have downloaded the tar.gz file for the augustus version 3.4.0 from github. 

Ran:
`tar -xzf augustus-3.4.0.tar.gz`

And get a new directory augustus-3.4.0.

It has the following directories:

auxprogs  bin  common.mk  config  Dockerfile  docs  examples  include  Makefile  mansrc  README.md  scripts  src  tests

In the bin directory is augustus, which looks to be executable :

-rwxrwxr-x 1 my_name my_name 3369832 Dec 11  2020 augustus

In Braker I have set the augustus bin, scripts and config paths, and it identifies and sets these.

It then fails, telling me that augustus is not executable on this machine. 

If I try running augustus directly (`./augustus`) I get:

./augustus: error while loading shared libraries: libboost_iostreams.so.1.71.0: cannot open shared object file: No such file or directory

I've tried installing this separately and pointing to it with a symbolic link in the bin folder. I've tried copying the libboost files for v1.74 from an anaconda installation of braker/augustus into the lib directory of the environment within which augustus sits (I had previously downloaded braker/augustus using anaconda but ran into issues getting Genemark to run with it, so changed to manually installing each one).

When I do:

`ldd augustus`

I get the following:

./augustus: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by ./augustus)
./augustus: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./augustus)
./augustus: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by ./augustus)
./augustus: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by ./augustus)
./augustus: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by ./augustus)
./augustus: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./augustus)
./augustus: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./augustus)
./augustus: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./augustus)
./augustus: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./augustus)
        linux-vdso.so.1 =>  (0x00007ffe7e5e0000)
        libboost_iostreams.so.1.71.0 => not found
        libgsl.so.23 => not found
        libcolamd.so.2 => /usr/lib64/libcolamd.so.2 (0x00007f57ef1b0000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f57eefa8000)
        libboost_serialization.so.1.71.0 => not found
        libmysqlclient.so.21 => not found
        libmysqlpp.so.3 => not found
        libsqlite3.so.0 => /usr/lib64/libsqlite3.so.0 (0x00007f57eed10000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007f57eea00000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f57ee770000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f57ee550000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f57ee1b0000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f57ef698000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f57edf88000)

So I tried setting a symbolic link to the libstdc++.so.6, but no luck.
Tried setting the LD_library_path in braker script to either the libboost_iostreams_1.71.0 or the libstdc++.so.6 and no luck with either.

I wondered if the Dockerfile needed to be run after using tar? (I have mainly been installing programs either via anaconda or simply by using tar, and have basically no experience of docker - I couldn't find it on our system and installed docker-py but can't find the 'docker' command within in...) 

Any help would be much appreciated! 

Thanks so much,
Jenni

**Comment by SheepwormJM** [comment]
Also, I've tried making ZIPINPUT and COMPGENEINPUT to 'false' in the common.mk file too and it doesn't seem to make any difference. As a side note - the common.mk claims the AUGVERSION is 3.3.3. Is this just a typo error or has something gone wrong somewhere?

**Comment by hmehlan** [comment]
The augustus-_version_.tar.gz files are intended as an easy way to download different AUGUSTUS versions.
The binaries inside will only be executable in rare cases where, among other things, all link dependencies are met.
How to create an executable AUGUSTUS binary is described in [docs/INSTALL.md](https://github.com/Gaius-Augustus/Augustus/blob/master/docs/INSTALL.md) (I would prefer to download the sources from github, as some improvements have been made since the 3.4.0 release.)
For Debian and Ubuntu there are packages in their repositories (see [README.md](https://github.com/Gaius-Augustus/Augustus/blob/master/README.md))
