### ISSUE TITLE
where is README.txt?

### ISSUE THREAD

**Issue by krabapple** [Gaius-Augustus/Augustus#303]
Invoking augustus without parameters or input brings up help for a limited set of parameters

at the end  there is this 

```

For a complete list of parameters, type "augustus --paramlist".
An exhaustive description can be found in the file README.TXT.
```

paramlist is a complete list but has no explanatory text

I cannot find README.TXT  -- a file with an exhaustive description of all AUGUSTUS parameters  -- anywhere in the installation . Where can I locate it?  

NB README.md does not contain an exhaustive description.

**Comment by MarioStanke** [comment]
The README.txt has been migrated to Markdown and split up by topics. The parameters are described here:
https://github.com/Gaius-Augustus/Augustus/blob/master/docs/RUNNING-AUGUSTUS.md
I will change the message.
