### ISSUE TITLE
explain use of 'initial' 'internal' 'terminal'  and 'single' exon output options

### ISSUE THREAD

**Issue by krabapple** [Gaius-Augustus/Augustus#304]
In the online manual there is this:

"Output options. Output predicted protein sequence, introns, start codons, stop codons. **Or use 'cds' in addition to 'initial', 'internal', 'terminal' and 'single' exon."**

Can you show me how I would employ the option indicated in bold, in an augustus command line?

**Comment by MarioStanke** [comment]
--cds=1/0 turns on/off CDS lines
--exonnames=1/0 turns on/off 'initial', 'internal', 'terminal' and 'single' lines

e.g. you use `--cds=1 --exonnames=1` to display both. I updated the description, because it became confusing after migrating to MarkDown.
