### ISSUE TITLE
Stop codon in protein sequence files generated by getAnnoFastaFromJoingenes.py

### ISSUE THREAD

**Issue by Lamm-a** [Gaius-Augustus/Augustus#311]
getAnnoFastaFromJoingenes.py is adding stop codons in the for of "*" to the end of protein sequences such as:

```
>file_1_file_1_g8482.t1
MEQWSIALVDFIVKLPNAYSYDVIMVVVDLYGKQAYFIPTHTTCSAMGATNLYQRNVWKL
HGLSEAYVSNQGPQFVADFIWELYQLLNVKLHTSTAYHLQFNSQTEHVNQELKQYLHLFC
NEH*
>file_1_file_1_g7827.t1
MESDSHNGASAPTMASTEATETVASGPLTAAIATKIAIPATFKASSSSSTEMTHVTSKCW
ADIMSSKEALSLQIDRWAD*
>file_1_file_1_g8218.t1
MDFVQSLDPSKLVLAETVLSFVISPFIAPPYNLAIFLFGTYVQENTETIQTMRIFTGLVG
VSALFDVLWMSTNEQNGFIKLLSILILLLKVPTFFALGLTLHHRGATFSGLGGQDLNGST
VWSMPVGFTSGGREGYQTVDEERPTNNPRPLASASLSTAPPPPGTYQVA*
```

Is there a way to stop this as it interproscan trip up seeing "*" in the sequence.

Generated with:
`getAnnoFastaFromJoingenes.py --filter -g $assembly -o $prefix -f $gtf`

EDIT:

Just saw #56 where you suggest to just remove the *.  However I am not following as to why the * is there is the first place?

**Comment by KatharinaHoff** [comment]
The * represents not-translated stop codon in protein sequences. It tells you that the protein sequence actually had a stop and is not truncated at that end. (Similarly, you might scan for a M at the beginning to make sure that it had a putative start.)
You can easily remove the stars before running interproscan:

cat proteins.fa | perl -pe 's/\*//;' > proteins_no_stop.fa

**Comment by Lamm-a** [comment]
Ahh okay so ending with a * is a good thing and those without are potentially truncated protein sequences?

Thank you very much!

**Comment by KatharinaHoff** [comment]
Yes. AUGUSTUS can predict incomplete genes (unless you turn that off). And you can either check in the codingseq or gff/gtf/gff3 file whether it's complete or incomplete, or you can check in the protein fasta when the untranslated stop codons are given.

**Comment by Lamm-a** [comment]
I think the correct sed is `perl -pe 's/\*//g'`  :)

**Comment by KatharinaHoff** [comment]
If the protein is translated correctly, there should be only one star in a
line. If not... you should probably check what's going on.

**Comment by Lamm-a** [comment]
I only have one star, but the sed from your #56 post worked over the above oddly!
