### ISSUE TITLE
Error running unsupervised GeneMark-ET training to generate template genes for training AUGUSTUS

### ISSUE THREAD

**Issue by guptapa** [Gaius-Augustus/Augustus#322]
Hi,
I'm getting following error recorded in gmes.log file while running unsupervised GeneMark-ET training and prediction to generate template genes for training AUGUSTUS:

/home/genome/augustus_training/braker/dependencies/gm_et_linux_64/gmes_petap.pl : [Mon Oct 18 13:47:29 2021] /home/genome/augustus_training/braker/dependencies/gm_et_linux_64/make_nt_freq_mat.pl --cfg /home/GuptaP/run.cfg --section donor_GT --format DONOR
/home/genome/augustus_training/braker/dependencies/gm_et_linux_64/gmes_petap.pl : [Mon Oct 18 13:47:29 2021] error

The standard out file details are:

check before run
create directories
commit input data
data report
commit training data
training data report
prepare initial model
get GC of sequence
GC 42
build initial ET model
error, no valid sequences were found
error on call: /home/genome/augustus_training/braker/dependencies/gm_et_linux_64/make_nt_freq_mat.pl --cfg /home/GuptaP/run.cfg
--section donor_GT --format DONOR

Need advice to solve this issue.

Thanks,
Parul

**Comment by MarioStanke** [comment]
This is a GeneMark or BRAKER issue. Please post it there.
