### ISSUE TITLE
gff2gbSmallDNA.pl error.

### ISSUE THREAD

**Issue by xiekunwhy** [Gaius-Augustus/Augustus#324]
Hi,

I got many error when runing gff2gbSmallDNA.pl, and the traingenes.gtf file is the results of GeneMark-EP.
traingenes.gtf_gff2gbSmallDNA.zip is the stderr file and traingenes.zip is the input gtf file.
[traingenes.gtf_gff2gbSmallDNA.zip](https://github.com/Gaius-Augustus/Augustus/files/7542169/traingenes.gtf_gff2gbSmallDNA.zip)
[traingenes.zip](https://github.com/Gaius-Augustus/Augustus/files/7542170/traingenes.zip)

Best,
Kun

**Comment by hmehlan** [comment]
Thank you very much for your comment. 
I have fixed the bugs that led to the error messages - see #331
This does not affect the output file of the script. This remains unchanged.
