### ISSUE TITLE
More genes predicted on the same positions

### ISSUE THREAD

**Issue by LeoVincenzi** [Gaius-Augustus/Augustus#326]
Hi everyone!
I'm having an issue with a prediction made with augustus. I have noticed that in the gff file generated by AUGUSTUS 3.3.3 there are some regions that predict more than one gene (but never more than two). Is that possible? I would expect that a region in a genome could codify for just one specific gene. I'm reflecting if I should remove the 'duplicates' or not. I'm also wondering why they are predicted separately and not one after the first one.

I send you an example:
#start gene g6161
Chr11   AUGUSTUS        gene    9052859 9055043 0.61    -       .       g6161
Chr11   AUGUSTUS        transcript      9052859 9055043 0.61    -       .       g6161.t1
Chr11   AUGUSTUS        stop_codon      9052859 9052861 .       -       0       "transcript_id ""g6161.t1"""
Chr11   AUGUSTUS        CDS     9052859 9052906 1       -       0       "transcript_id ""g6161.t1"""
#end gene g6161
#start gene g6170
Chr11   AUGUSTUS        gene    9052859 9055043 0.59    -       .       g6170
Chr11   AUGUSTUS        transcript      9052859 9055043 0.59    -       .       g6170.t1
Chr11   AUGUSTUS        stop_codon      9052859 9052861 .       -       0       "transcript_id ""g6170.t1"""
Chr11   AUGUSTUS        CDS     9052859 9052906 1       -       0       "transcript_id ""g6170.t1"""
#end gene g6170

or again 

#start gene g2827
Chr01   AUGUSTUS        gene    10097384        10099077        0.92    -       .   g2827
Chr01   AUGUSTUS        transcript      10097384        10099077        0.92    -   .g2827.t1
Chr01   AUGUSTUS        stop_codon      10097384        10097386        .       -   0"transcript_id ""g2827.t1"""
Chr01   AUGUSTUS        CDS     10097384        10098664        0.95    -       0   "transcript_id ""g2827.t1"""
#end gene g2827
#start gene g2834
Chr01   AUGUSTUS        gene    10097384        10099077        0.74    -       .   g2834
Chr01   AUGUSTUS        transcript      10097384        10099077        0.74    -   .g2834.t1
Chr01   AUGUSTUS        stop_codon      10097384        10097386        .       -   0"transcript_id ""g2834.t1"""
Chr01   AUGUSTUS        CDS     10097384        10098664        0.99    -       0   "transcript_id ""g2834.t1"""
#end gene g2834

Maybe somenone can clarify me the situation.
Thank you for the consideration!

**Comment by LeoVincenzi** [comment]
Hi Everyone!
I have also checked those regions on IGV and I have realized that the gene visualized on one of those offending regions corresponds to the second one predicted there. 
It seems that, after a while that the software has predicted a gene on aregion, the software goes back on that region and predict again the same gene, but changing the id (assigns in sequential order). 
That makes me think that I need to remove those duplicates in order to not have a higher number of genes than the effective number of predicted genes.

I'm wondering if anybody else has noticed this issue or that the developers could provide me an explenation of that strange bias.
Thank you!

**Comment by MarioStanke** [comment]
That should not happen from within `augustus`. Are you using a pipeline that calls `augustus`? What is your command line?

**Comment by LeoVincenzi** [comment]
I'm actually using augustus pipeline. In particular, the command is:

augustus --extrinsicCfgFile=reference.cgf --genemodel=partial --hintsfile=hints.gff --species=BUSCO_ref_vulgaris --allow_hinted_splicesites=atac --softmasking=on

I have tried to use the different option for --genemodel, but even if the numbers of predicted genes decreases, there are always some 'repeated genes'

**Comment by MarioStanke** [comment]
If you are only calling `augustus` I would ask you to make an example input available. It would then be really unexpected.

If you are running another command as well, e.g. a script that calls `augustus` multiple times, then let us know what it is. There are many pipelines that use augustus.

**Comment by LeoVincenzi** [comment]
Looking at your 'Predicting Genes in Single Genomes with AUGUSTUS' I have applied commands descripted in the Supplementary Protocol 20 for the data parallelization. So I have first splitted the genome, obtained the necessary summary.out and chr.lst requested and then created a job list to run predictions in parallel.

**Comment by MarioStanke** [comment]
The splitting is done with overlaps because you would otherwise break up genes. This creates duplicate gene predictions or fractions of genes. Afterwards, you have to run `join_aug_pred.pl`, which should clean the redundancies.

**Comment by LeoVincenzi** [comment]
Yes, I have already filtered my outputs with join_aug_pred.pl, but I have found those repetitive outputs after that operation. Anyway, I am actually annotating another genome and I'm still facing the same issue, so I think it is due to something that has nothing to do with the data used.

**Comment by MarioStanke** [comment]
I suspect that you may have fed join_aug_pred.pl the concatenated GFF files in another order than the one produced by the splitting. That could happen if you use the `*` on the command line which sorts lexicographically, rather than a for loop. I suggest, you check your command that produced the input to `join_aug_pred.pl` for the order of files.

**Comment by LeoVincenzi** [comment]
Great! I was actually using a cat results/* to concatenate my outputs my outputs, but using the for loop I discard those duplicated genes I had before. However, the line which is present in your guidlines:
```
for x in ‘cat jobs.lst‘
do
cat $x | perl -ne ’if(m/--outfile=(\S*) --errfile/){print $1} | \
join_aug_pred.pl > augustus.gff
done
```
didn't works for me immediately. I had to make an intermediate list with the output in the order of the loop and then I had modified this list as an executable bash script to cat each line in a new intermediate gff which i have finally run into `join_aug_pred.pl`... Don't know if there's a more fast way to make you're original lines work.

**Comment by MarioStanke** [comment]
Indeed there is an apparent error in this code snipped in our book. This should do it:
```
for x in `cat jobs.lst`
do
cat $x | perl -ne 'if(m/--outfile=(\S*) --errfile/){print $1}'  | xargs cat
done | join_aug_pred.pl > augustus.gff
```

Your alternative of first creating the list of files in the same order as the jobs were created and second concatenating them may be more robust, even.
