### ISSUE TITLE
etraining Segmentation fault（core dumped）

### ISSUE THREAD

**Issue by ypchan** [Gaius-Augustus/Augustus#332]
Dear Augustus‘s authors，

I installed braker2 using conda. But when I use etraining for new species, the error happend like below:

`etraining --species=colletotrichum_tofieldiae Colletotrichum_tofieldiae_ct0861.gb.train`
Segmentation fault (core dumped)

My augustus version:
![image](https://user-images.githubusercontent.com/33273919/149627218-162f5c08-ec18-4e65-8dbe-518f09eaa235.png)

Test file:
[Colletotrichum_tofieldiae_ct0861.gb.train.zip](https://github.com/Gaius-Augustus/Augustus/files/7875266/Colletotrichum_tofieldiae_ct0861.gb.train.zip)

Thanks
Yanpeng

**Comment by KatharinaHoff** [comment]
Please clone the current AUGUSTUS from Github and compile locally. The
problem might disappear. If not, please let us know.

Katharina

**Comment by ypchan** [comment]
Dear Dr. KatharinaHoff,

According to your suggestion, it works. Thanks for your timely help.

Yanpeng
