### ISSUE TITLE
Could not locate directory AUGUSTUS_CONFIG_PATH

### ISSUE THREAD

**Issue by veedeeve** [Gaius-Augustus/Augustus#345]
Tried to run 
`augustus --protein=on --gff3=on --species=aspergillus_fumigatus aspergillus_fumigatus.fna.gz `

But I would get an error that the AUGUSTUS_CONFIG_PATH is not located/ not a directory

Checked the file and found augustus as an executable file, and was able to open the file.

Installed augustus using mamba into a conda environment.

**Comment by KatharinaHoff** [comment]
You need to export the path to the config directory of Augustus.

export AUGUSTUS_CONFIG_PATH=/a/writable/location/Augustus/config

The config directory contains several directories and files. It should be
writable if you intend to perform any kind of training.

veedeeve ***@***.***> schrieb am Di. 28. Juni 2022 um 06:59:
