### ISSUE TITLE
Can I use related species for gene prediction step?

### ISSUE THREAD

**Issue by mathavanpu** [Gaius-Augustus/Augustus#355]
Hi
I am working on whole genome analysis of _**Aspergillus neoindicus**_. I used the following command,
augustus --species=**aspergillus_nidulans**  Iso.contigs.fasta > augustus.abinitio.gff , 

My species is not listed  in the species option, can I use the relative species for the analysis

**Comment by MarioStanke** [comment]
Yes, as a rule of thumb I expect it to be of little effect on accuracy if the average protein identify of orthologs is 80% or above (that is about the distance between human and mouse and also between Drosophila melanogaster and Drosophila ananassae).
It could work beyond and if none of the species with parameters are close the closest might not be the best.
