### ISSUE TITLE
Augustus Makefile after git pull update

### ISSUE THREAD

**Issue by KatharinaHoff** [Gaius-Augustus/Augustus#36]
In the current version, a "make" will fail after a source code update:

make
mkdir -p bin
mkdir: cannot create directory ‘bin’: File exists
make: *** [all] Error 1

Maybe we should add a "rm -r bin" in case bin exists?

**Comment by MarioStanke** [comment]
That is weird. -p should make it ignore that the directory exists (besides
creating parent dirs).

Am So., 2. Dez. 2018 um 18:10 Uhr schrieb Katharina Hoff <
notifications@github.com>:

**Comment by KatharinaHoff** [comment]
-p is not a parameter of rm on CentOS:

OPTIONS
       Remove (unlink) the FILE(s).

       -f, --force
              ignore nonexistent files and arguments, never prompt

       -i     prompt before every removal

       -I     prompt once before removing more than three files, or when removing recursively; less intrusive  than  -i,  while
              still giving protection against most mistakes

       --interactive[=WHEN]
              prompt according to WHEN: never, once (-I), or always (-i); without WHEN, prompt always

       --one-file-system
              when  removing  a  hierarchy  recursively, skip any directory that is on a file system different from that of the
              corresponding command line argument

       --no-preserve-root
              do not treat '/' specially

       --preserve-root
              do not remove '/' (default)

       -r, -R, --recursive
              remove directories and their contents recursively

       -d, --dir
              remove empty directories

       -v, --verbose
              explain what is being done

       --help display this help and exit

       --version
              output version information and exit

**Comment by KatharinaHoff** [comment]
The issue was caused by a faulty cifs mount on our cluster. I am closing it because rmdir -p should work, unless access to the harddrive is impossible (temporarily).
