### ISSUE TITLE
Using prothint output in augustus

### ISSUE THREAD

**Issue by ShakunthalaNatarajan** [Gaius-Augustus/Augustus#362]
I have obtained the prothint_augustus.gff file from prothint. I used it for gene prediction with augustus. But  an error shows up as:

Unknown hint feature 'P'. Ignoring it. For a list of 17 allowed features see, /config/extrinsic.cfg. The command I used to run augustus was:

augustus --hintsfile=prothint_augustus.gff --extrinsicCfgfile=extrinsic.cfg --species=species_name genome.fasta > output.gff

Is augustus ignoring my protein hints? Should I call this feature type in any other manner? Please help!

**Comment by MarioStanke** [comment]
`Augustus/config/extrinsic/extrinsic.cfg` has by default only hints of types M=manual and RM=repeatmasking.
You could use instead `extrinsic.MP.cfg` or another one with P.
The reason that there is not one configuration for all sources of hints is that the absence of hints is taken as evidence against a gene structure when one has searched for the evidence.
