### ISSUE TITLE
Mus musculus

### ISSUE THREAD

**Issue by isnmn** [Gaius-Augustus/Augustus#390]
Hi,
I'm trying to use mm as it is a close relative of my organism but weirdly, I couldn't find mm in Augustus species as well.
There are no "clear" instructions to train Augustus, so could you please guide me how can I use mus musculus in Augustus?

**Comment by KatharinaHoff** [comment]
We usually use human parameters for all mammals without retraining. We have
(unpublished) mouse parameters from training via GALBA and BRAKER3, but
they are not necessarily better.

isnmn ***@***.***> schrieb am Do. 18. Mai 2023 um 12:41:
