### ISSUE TITLE
Augustus CGP mode, terminate called after throwing an instance of 'std::out_of_range' 

### ISSUE THREAD

**Issue by Nikhilgunala** [Gaius-Augustus/Augustus#394]
error : terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 12157) >= this->size() (which is 3)
Aborted 
 
while running AUGUSTUS in cgp Mode 
command :  augustus --species=verticillium_longisporum1 --treefile=tree.nwk --alnfile=verticilliumtopani2.maf   --dbaccess=verticiliumtopani2.db --speciesfilenames=newverticiliumtopani2.tbl

can someone help me in this please 

Thank you

**Comment by Nikhilgunala** [comment]
@KatharinaHoff @MarioStanke

**Comment by KatharinaHoff** [comment]
Please provide a minimal example data set that causes this issue.

**Comment by Nikhilgunala** [comment]
I'm working on genome annotation of Verticillium dahliae species with AUGUSTUS  CGP mode , followed the AUGUSTUS  CGP tutorial and created newick file, Verticillium_dahliae.db , Verticilliumdahliae.tbl , Verticilliumdahliae.maf for Verticillium dahliae species of five different strains wholes genomes and struck while running final 


command : augustus --species=verticillium_longisporum1 --treefile=tree.nwk --alnfile=aln.maf --dbaccess=verticilium.db --speciesfilenames=verticilium.tbl  


error : terminate called after throwing an instance of 'std::out_of_range'
what(): vector::_M_range_check: __n (which is 12157) >= this->size() (which is 3)
Aborted

<img width="298" alt="speciesnames" src="https://github.com/Gaius-Augustus/Augustus/assets/90795103/1fadf432-e7bb-47da-a1b9-8202e9c59a03">

@KatharinaHoff

**Comment by Nikhilgunala** [comment]
can someone help me in this please 

thank you

**Comment by MarioStanke** [comment]
@StepanSaenko, can you please run these tutorial commands and see whether you get the error as well? If you can reproduce the error, I can probably fix it.

**Comment by MarioStanke** [comment]
I see. Large data is not a problem per see as we run it on 20 vertebrate genomes. Can you then follow Katharina's request and give us a small part of your data as well as the command line where the error occurs?

**Comment by Nikhilgunala** [comment]
> Please provide a minimal example data set that causes this issue.
@KatharinaHoff 
yes, I have sent minimal data through mail, can you please check 
thank you

**Comment by StepanSaenko** [comment]
Could you please send a copy to stepan.saenko@uni-greifswald .de

**Comment by StepanSaenko** [comment]
> what(): vector::_M_range_check: __n (which is 12157) >= this->size() (which is 3)

This error was caused because the filename was "12157.fa" and the same in the .nwk file. Augustus was expecting of 12157 elements, but has only 3.

**Comment by MarioStanke** [comment]
I see. There is a parsing error because the (automatically generated) parser (from a formal language) assumed the number is  a distance. It is still good to catch this error and write an error message like: "Could not parse the newick file, make sure to let file names start with a letter". @StepanSaenko, can you do this, please?
