### ISSUE TITLE
Makefile74 error; but Augustus file created in src; Is my installation complete ?

### ISSUE THREAD

**Issue by sankadinesh** [Gaius-Augustus/Augustus#41]
![augustus error](https://user-images.githubusercontent.com/43870684/51165550-9aba4280-18c6-11e9-9bee-1b94e4a99528.jpg)
![augustus error 2](https://user-images.githubusercontent.com/43870684/51165551-9beb6f80-18c6-11e9-980c-5271dcb09cd8.jpg)
Please help
Thanks
Regards,
Dinesh

**Comment by KatharinaHoff** [comment]
I believe the missing bin directory has been added somewhere down the line since this issue was created.
