### ISSUE TITLE
Couldn't generate XXX_exon_probs.pbl in the directory "config/species/XXX/"

### ISSUE THREAD

**Issue by yoshi-ko** [Gaius-Augustus/Augustus#43]
In BRAKER pipeline, I got augustus.hints.stderr

path_to_augustus/config/../bin/augustus: ERROR
ExonModel: Couldn't open file /path_to_augustus/config/species/XXX/XXX_exon_probs.pbl

I searched XXX_exon_probs.pbl in the directory, but I couldn't find it.
However, other files XXX_metapars.cfg, XXX_metapars.cgp.cfg, XXX_metapars.utr.cfg, XXX_parameters.cfg and XXX_weightmatrix.txt exist in the directory.

**Comment by MarioStanke** [comment]
1. This is not an issue of augustus itself as the input file is missing.
2. It sounds that the other training output files XXX_intron_probs.pbl, XXX_igenic_probs.pbl are also not there and the training has not finished successfully. 

I suggest you examine the BRAKER log files for any errors or suspicious observations, also earlier, e.g. (near) empty alignment files. If you repost a BRAKER issue, please be much more specific. Ideally give us a command line, the version and some data to reproduce the error.

**Comment by yoshi-ko** [comment]
Thank you for your advice.
I will check errors and alignment files.

**Comment by Hongchang-Gu** [comment]
excuse me~yoshi-ko
Now I meeting a same error in MY work.
Specifically，that‘s 
‘UtrModel::readProbabilities: Couldn't open file chicken_utr_probs.pbl’
So I want to ask you that how to solve this issue.
THANKS A LOT!

**Comment by MarioStanke** [comment]
Chicken does not have a UTR model. You can predict the protein coding
regions only (--UTR=off).

Best, Mario

Am Do., 9. Mai 2019 um 04:05 Uhr schrieb Hongchang-Gu <
notifications@github.com>:
