### ISSUE TITLE
bam2hints does not give the information wether the hint is on forward stand or reverse strand

### ISSUE THREAD

**Issue by dukecomeback** [Gaius-Augustus/Augustus#44]
When use bam2hints to produce hint file from tophat or hisat bam, the result won't tell if the hint is on forward or reverse strand, would that be a problem for the final running of Augustus?
"
_HiC_scaffold_25 b2h     intron  2629    10234   0       .       .       pri=4;src=E
HiC_scaffold_25 b2h     intron  5437    5663    0       .       .       mult=2;pri=4;src=E
HiC_scaffold_25 b2h     intron  10721   11018   0       .       .       mult=2;pri=4;src=E
HiC_scaffold_25 b2h     intron  11131   12090   0       .       .       pri=4;src=E
HiC_scaffold_25 b2h     intron  12235   26531   0       .       .       pri=4;src=E
HiC_scaffold_25 b2h     intron  26355   26531   0       .       .       mult=2;pri=4;src=E
HiC_scaffold_25 b2h     intron  26719   32677   0       .       .       mult=3;pri=4;src=E
HiC_scaffold_25 b2h     intron  32822   36077   0       .       .       mult=2;pri=4;src=E
HiC_scaffold_25 b2h     intron  36287   37007   0       .       .       mult=3;pri=4;src=E
HiC_scaffold_25 b2h     intron  37282   38301   0       .       .       pri=4;src=E_
"

**Comment by KatharinaHoff** [comment]
This is not a bug. By nature, you don't see whether the spliced alignment corresponds to forward or reverse strand. You can make a safe guess by checking for donor/acceptor splice site pattern, and thus assign a strand. in BRAKER, you find a script https://github.com/Gaius-Augustus/BRAKER/blob/master/scripts/filterIntronsFindStrand.pl that does this for you. AUGUSTUS doesn't require you to filter the intron hints, though. It will internally check whether there is a valid splice site pattern, or not.
