### ISSUE TITLE
augustus do not follow hints

### ISSUE THREAD

**Issue by dukecomeback** [Gaius-Augustus/Augustus#47]
### Here is the a output from augustus (notice the bold line)
64_tag  AUGUSTUS        gene    1248552 1250684 0.95    -       .       g55
64_tag  AUGUSTUS        transcript      1248552 1250684 0.95    -       .       g55.t1
64_tag  AUGUSTUS        stop_codon      1248552 1248554 .       -       0       transcript_id "g55.t1"; gene_id "g55";
64_tag  AUGUSTUS        intron  1248731 1248843 1       -       .       transcript_id "g55.t1"; gene_id "g55";
64_tag  AUGUSTUS        intron  1249034 1249124 1       -       .       transcript_id "g55.t1"; gene_id "g55";
64_tag  AUGUSTUS        intron  1249249 1249653 1       -       .       transcript_id "g55.t1"; gene_id "g55";
64_tag  AUGUSTUS        intron  1249826 1250040 1       -       .       transcript_id "g55.t1"; gene_id "g55";
**64_tag  AUGUSTUS        intron  1250082 1250142 0.95    -       .       transcript_id "g55.t1"; gene_id "g55";**
64_tag  AUGUSTUS        intron  1250175 1250250 1       -       .       transcript_id "g55.t1"; gene_id "g55";
64_tag  AUGUSTUS        intron  1250406 1250491 1       -       .       transcript_id "g55.t1"; gene_id "g55";
64_tag  AUGUSTUS        CDS     1248552 1248730 1       -       2       transcript_id "g55.t1"; gene_id "g55";
64_tag  AUGUSTUS        CDS     1248844 1249033 1       -       0       transcript_id "g55.t1"; gene_id "g55";
64_tag  AUGUSTUS        CDS     1249125 1249248 1       -       1       transcript_id "g55.t1"; gene_id "g55";
64_tag  AUGUSTUS        CDS     1249654 1249825 1       -       2       transcript_id "g55.t1"; gene_id "g55";
64_tag  AUGUSTUS        CDS     1250041 1250081 0.95    -       1       transcript_id "g55.t1"; gene_id "g55";
64_tag  AUGUSTUS        CDS     1250143 1250174 1       -       0       transcript_id "g55.t1"; gene_id "g55";
64_tag  AUGUSTUS        CDS     1250251 1250405 1       -       2       transcript_id "g55.t1"; gene_id "g55";
64_tag  AUGUSTUS        CDS     1250492 1250684 1       -       0       transcript_id "g55.t1"; gene_id "g55";
64_tag  AUGUSTUS        start_codon     1250682 1250684 .       -       0       transcript_id "g55.t1"; gene_id "g55";
### Here is the hint it used (for CDSpart and exonpart I cut off 15 from both site)
64_tag  b2h     intron  1249826 1250040 .       .       .       mult=8519;pri=4;src=E
64_tag  b2h     intron  1249826 1250040 .       .       .       mult=9944;pri=4;src=E
64_tag  GeneWise        intron  1249826 1250040 .       -       .       grp=64_tag:1250684:1248552-F-ENSDARP00000037871.5;pri=5;src=WISE
64_tag  xnt2h   intron  1249826 1250040 .       -       .       grp=ENSGMOP00000009388.1;pri=4;src=XNT
**64_tag  assembler-sample_mydb_pasa      exonpart        1250056 1250159 .       -       .       grp=align_938114;pri=4;src=W
64_tag  Cufflinks       exonpart        1250056 1250159 .       -       .       grp=CUFF.208163.1;pri=4;src=W
64_tag  GeneWise        CDSpart 1250056 1250159 .       -       0       grp=64_tag:1250684:1248552-F-ENSDARP00000037871.5;pri=5;src=WISE
64_tag  xnt2h   CDSpart 1250056 1250159 .       -       .       grp=ENSGMOP00000009388.1;pri=4;src=XNT
64_tag  SNAP    CDSpart 1250065 1250162 .       +       .       grp=64_tag-snap.184;pri=3;src=AB
64_tag  GeneMark.hmm    CDSpart 1250086 1250159 .       -       0       grp=15413_g;pri=3;src=AB
64_tag  SNAP    CDSpart 1250086 1250159 .       -       .       grp=64_tag-snap.183;pri=3;src=AB**
64_tag  b2h     intron  1250175 1250250 .       .       .       mult=10868;pri=4;src=E
64_tag  b2h     intron  1250175 1250250 .       .       .       mult=11309;pri=4;src=E
64_tag  GeneWise        intron  1250175 1250250 .       -       .       grp=64_tag:1250684:1248552-F-ENSDARP00000037871.5;pri=5;src=WISE
64_tag  xnt2h   intron  1250175 1250250 .       -       .       grp=ENSGMOP00000009388.1;pri=4;src=XNT
64_tag  SNAP    stop    1250245 1250409 .       +       .       grp=64_tag-snap.184;pri=3;src=AB
64_tag  assembler-sample_mydb_pasa      exonpart        1250266 1250390 .       -       .       grp=align_938114;pri=4;src=W
64_tag  Cufflinks       exonpart        1250266 1250390 .       -       .       grp=CUFF.208163.1;pri=4;src=W
64_tag  GeneMark.hmm    CDSpart 1250266 1250390 .       -       2       grp=15413_g;pri=3;src=AB
64_tag  GeneWise        CDSpart 1250266 1250390 .       -       2       grp=64_tag:1250684:1248552-F-ENSDARP00000037871.5;pri=5;src=WISE
64_tag  SNAP    CDSpart 1250266 1250390 .       -       .       grp=64_tag-snap.183;pri=3;src=AB
64_tag  xnt2h   CDSpart 1250266 1250390 .       -       .       grp=ENSGMOP00000009388.1;pri=4;src=XNT
64_tag  b2h     intron  1250338 1263759 .       .       .       pri=4;src=E
64_tag  b2h     intron  1250405 1250491 .       .       .       mult=11;pri=4;src=E
64_tag  b2h     intron  1250406 1250491 .       .       .       mult=13970;pri=4;src=E
64_tag  b2h     intron  1250406 1250491 .       .       .       mult=14529;pri=4;src=E
64_tag  GeneWise        intron  1250406 1250491 .       -       .       grp=64_tag:1250684:1248552-F-ENSDARP00000037871.5;pri=5;src=WISE
64_tag  xnt2h   intron  1250406 1250491 .       -       .       grp=ENSGMOP00000009388.1;pri=4;src=XNT
64_tag  SNAP    start   1250492 1250684 .       -       .       grp=64_tag-snap.183;pri=3;src=AB
64_tag  assembler-sample_mydb_pasa      exonpart        1250507 1250684 .       -       .       grp=align_938114;pri=4;src=W
64_tag  Cufflinks       exonpart        1250507 1250684 .       -       .       grp=CUFF.208163.1;pri=4;src=W
64_tag  GeneMark.hmm    CDSpart 1250507 1250669 .       -       0       grp=15413_g;pri=3;src=AB
64_tag  GeneWise        CDSpart 1250507 1250669 .       -       0       grp=64_tag:1250684:1248552-F-ENSDARP00000037871.5;pri=5;src=WISE
64_tag  xnt2h   CDSpart 1250507 1250669 .       -       .       grp=ENSGMOP00000009388.1;pri=4;src=XNT
64_tag  GeneMark.hmm    start   1250682 1250684 .       -       0       grp=15413_g;pri=3;src=AB
64_tag  b2h     intron  1250694 1251791 .       .       .       mult=7;pri=4;src=E
64_tag  b2h     intron  1250694 1251791 .       .       .       mult=8;pri=4;src=E
64_tag  b2h     intron  1250700 1251791 .       .       .       mult=10158;pri=4;src=E
64_tag  b2h     intron  1250700 1251791 .       .       .       mult=10495;pri=4;src=E
64_tag  b2h     intron  1250700 1251819 .       .       .       mult=5;pri=4;src=E
64_tag  b2h     intron  1250700 1251819 .       .       .       mult=5;pri=4;src=E

----------------------------------------------------
Hence you could see that the intron in bold should never be exist, but augustus is so stubborn to give that intron out, why is that?
I have tried many times with different hint parameters, the intron is always there.
Only this hint, the others are following hint well.

**Comment by MarioStanke** [comment]
There are at least two possible reasons:

1. The hints are 'soft', i.e. the bonus of src=AB CDSpart hints is not practically infinite. This is set in the extrinsic.cfg file. We usually use src=M for 'manual' (hard) hints.
2. There is no admissible gene structure that satisfies all given hints, e.g. because there would be an in-frame stop codon or no valid spice site pattern.

If neither of above is the case, it could be a bug. In that case please post the data (sequence, parameter files, extrinsic.cfg, hints) and command line required to reproduce the bug.

**Comment by dukecomeback** [comment]
@MarioStanke Sorry about my delayed reply.
I manually delete the intron (actually count the intron as CDS), as you expect, in-frame stop codons show up. Sorry about the false alarm and thank you very much for your suggestions and help.
