### ISSUE TITLE
Question: How to submit a species model generated with braker2 

### ISSUE THREAD

**Issue by OnlyHigh** [Gaius-Augustus/Augustus#56]
Hi, 
I generated a model of _Purpureocillium lilacinum_ with braker2 based in two RNAseq libraries, 
If I want to submit it, what I have to do? 

Cheers, 
Luis Alfonso.

**Comment by KatharinaHoff** [comment]
Hi Luis,

if you send me the parameters (e.g. as compressed directory), I will add
them to the repository. (We are working on a more convenient solution on
the long run, but that's still in the future.)

Please also send me a short description on how the parameter set was
obtained (e.g. the braker call and for example genome version, SRA
identifiers of RNA-Seq data, aligner, etc.). Just a few lines.

Thank you!

Katharina

**Comment by OnlyHigh** [comment]
Done! 
Check your email,
Cheers, 
Luis Alfonso.
