### ISSUE TITLE
join_aug_pred.pl script generates empty output file

### ISSUE THREAD

**Issue by PradoN** [Gaius-Augustus/Augustus#73]
I am following the guidelines set out in Hoff and Stanke 2019 (doi: 10.1002/cpbi.57) for parallelization of a large genome into smaller tasks, using augustus/3.3. I need to merge my augustus output from over 130 different jobs (each file shows gene predictions) into one gff file. However, when I try to run the join_aug_pred.pl script to merge all of the output, it creates an empty file. Below is my script:

 for i in {1..132}; do cat filename_augustus.$i.out | join_aug_pred.pl > filename.augustus.gff; done

Everything has run successfully up until this point. Not sure what can be going wrong, any guidance you can provide would be much appreciated.

Thanks,
Natalia

**Comment by PradoN** [comment]
I should also add that the log file for the job says that the merge completed successfully, and does not give any errors.

**Comment by KatharinaHoff** [comment]
Have you tried >> instead of >?

**Comment by PradoN** [comment]
Yes, I have tried that and it still creates an empty file.

I have also tried separating the tasks by running the concatenate command first, then running the join_aug_pred.pl script and the resulting gff file is still empty.

**Comment by KatharinaHoff** [comment]
Has the input to join_aug_pred.pl any content? Can you post an excerpt with
9 column gff content? (The hash lines are less interesting for the script)

**Comment by PradoN** [comment]
Hi,

I have attached a file with an excerpt from one of the files.

[output file 1.docx](https://github.com/Gaius-Augustus/Augustus/files/3427393/output.file.1.docx)

**Comment by PradoN** [comment]
Hi Katharina,

Do you have any suggestions on how I can merge my different files with the join_aug script?

Many thanks,
Natalia

**Comment by KatharinaHoff** [comment]
I am on vacation. I will look into it when I am back.

**Comment by PradoN** [comment]
Ok, thank you!

**Comment by PradoN** [comment]
Hi Katharina,

I am sorry to keep bothering you, but I haven't been able to resolve the issue with the join_aug script. Any guidance you could provide would be much appreciated.

Many thanks,
Natalia

**Comment by albodrug** [comment]
I ran also into the same issue, and finally did it like this:
```
for i in {1..132}; do cat augustus.$i.out  ; done > concatenated_augustus.gff
join_aug_pred.pl < concatenated_augustus.gf f> joined_augustus.gff; done
```

**Comment by PradoN** [comment]
Thank you! I will try that.

On Aug 22, 2019 5:04 AM, AlBodrug <notifications@github.com> wrote:

I ran also into the same issue, and finally did it like this:

for i in {1..132}; do cat augustus.$i.out  ; done > concatenated_augustus.gff
join_aug_pred.pl < concatenated_augustus.gf f> joined_augustus.gff; done

**Comment by hmehlan** [comment]
Please have a look the way prediction joining is done in  [scripts/autoAugPred.pl](https://github.com/Gaius-Augustus/Augustus/blob/master/scripts/autoAugPred.pl#L413). It is ultimately the same thing @albodrug has proposed.

Meanwhile the autoAugPred.pl is extended to run prediction in parallel. You could give this script a try, e.g. by 
`autoAugPred.pl --cpus=8 --singleCPU --workingdir=/.../autoAug --predictionresultsdir=/.../autoAug/autoAugPred --species=arabidopsis --genome=/.../genome.fa --augustusoptions=" --UTR=off --strand=both --sample=100 --genemodel=partial --hintsfile=/.../est.hints --extrinsicCfgFile=/.../extrinsic.ME.cfg --codingseq=on --exonnames=on"`
