### ISSUE TITLE
Error fix_in_frame_stop_codon_genes.py

### ISSUE THREAD

**Issue by KatharinaHoff** [Gaius-Augustus/Augustus#82]
@SvitlanaLukicheva open an issue in BRAKER at https://github.com/Gaius-Augustus/BRAKER/issues/71 that is an Augustus scripts issue.

fix_in_frame_stop_codon_genes.py was called with a command of type

`fix_in_frame_stop_codon_genes.py -g genome.fa -t augustus.hints.gtf -b bad_genes.lst -o augustus.hints_fix_ifs_ -s GQ_RNASeq_214 -m on --UTR off --print_utr off -H hintsfile.gff -e rnaseq.cfg `

by BRAKER (path variables are omitted here).

It failed while using grep to find hints in the hintsfile.

Log information:

The file contains 1336 lines with the content:
`grep ctg1467 hintsfile.gff Suceeded in executing command.`

and finally the following error:

Error in file fix_in_frame_stop_codon_genes.py at line 243: 

```
Return code of subprocess was 1
['/bin/grep', 'ctg1467', '/mnt/fhgfs/users/s/l/slukiche/genome_annotati   1337 on/gq/braker/2.1.4/rnaseq_only/braker/hintsfile.gff']
```

@Anica94  : Do you have any idea how that is possible?

**Comment by KatharinaHoff** [comment]
Issue was fixed by @Anica94 in commit https://github.com/Gaius-Augustus/Augustus/commit/49978fa94ff197cd3dea82cce01c443c95a48b55 . Closing issue.

**Comment by ovidp** [comment]
Hi. What do you mean with closed issue? I have the same error after waiting for 3 days for braker to finish and blocking important cluster resources. What do we need to do to not have this error and failed augustus/braker? Thanks

**Comment by Anica94** [comment]
Where and when did you download Augustus? 
With the new version of fix_in_frame_stop_codon_genes.py (after Sep 17) the error should not appear.

**Comment by ovidp** [comment]
Augustus 3.3.3 was installed on 28.11 from github. The error I have replicate now in several analyses is reported in  fix_IFS_log_XXXXXXX (X different depending on the run) for example as:

Error in file /apps/augustus/3.3.3/scripts/fix_in_frame_stop_codon_genes.py at line 243: Return code of subprocess was 1['/usr/bin/grep', 'scaffold593', '/scratch/braker/hintsfile.gff']

However the fix_in_frame_stop_codon_genes_augustus.log is empty and the same happens with fix_in_frame_stop_codon_genes_augustus.err
Thanks

**Comment by Anica94** [comment]
You should clone from GitHUB instead of clicking on download. Then you get the current version and it should work.

**Comment by ovidp** [comment]
Yes, this is correct. Cloning from Github directly solves the problem. Thank you
