### ISSUE TITLE
Badly placed ()'s.

### ISSUE THREAD

**Issue by guptapa** [Gaius-Augustus/Augustus#86]
I'm trying to remove redundant gene structures from trainng genes. To pull the transcripts names of training genes I ran following command:
cat RNA-Seq_geneStructure.gb | perl -ne if(m/gene/\/gene=\‘‘(S+)\’’/){\ print ‘‘\’’‘‘.$1.’’\‘‘\n’’;} | sort -u > traingenes.lst

& got this errror msg: Badly placed ()'s.

please suggest where I'm doing wrong and how to fix the script?

**Comment by KatharinaHoff** [comment]
The space followed by a backslash at the end of line indicates that the
command proceeds in the next line. The space and the backslash need to be
removed prior execution, they were merely inserted to improve readability
on A4 paper format (which is too narrow to contain full length commands).
Try:

cat RNA-Seq_geneStructure.gb | perl -ne if(m/\/gene=\‘‘(S+)\’’/){print
‘‘\’’‘‘.$1.’’\‘‘\n’’;} | sort -u > traingenes.lst

Katharina

**Comment by guptapa** [comment]
I tried the the code (as you suggested above) after removing space and backslash but got same error again.
code:
cat RNA-Seq_geneStructure.gb | perl -ne if(m/\/gene=\‘‘(S+)\’’/){print
‘‘\’’‘‘.$1.’’\‘‘\n’’;} | sort -u > traingenes.lst
error:
Badly placed ()'s.

**Comment by KatharinaHoff** [comment]
There are quotation marks missing:

cat RNA-Seq_geneStructure.gb | perl -ne 'if(m/\/gene=\‘‘(S+)\’’/){print
‘‘\’’‘‘.$1.’’\‘‘\n’’;}' | sort -u > traingenes.lst

**Comment by guptapa** [comment]
Ahh.....sorry I missed quotation marks.

with quotation mark:
cat RNA-Seq_geneStructure.gb | perl -ne 'if(m/\/gene=\‘‘(S+)\’’/){print
‘‘\’’‘‘.$1.’’\‘‘\n’’;}' | sort -u > traingenes.lst

error:
Unmatched '.

**Comment by KatharinaHoff** [comment]
When you copy commands from the pdf manuscript, you get "weird quotation marks".

I have double checked, the command

`cat RNA-Seq_geneStructure.gb |  perl -ne 'if(m/\/gene=\"(\S+)\"/){print "\"".$1."\"\n";}' | sort -u > traingenes.lst`

works. But it only works if you use the correct double quotation marks from your keyboard, not the pasted ones from the PDF.
