### ISSUE TITLE
Unmatched '.

### ISSUE THREAD

**Issue by guptapa** [Gaius-Augustus/Augustus#91]
Hi,
when I use this code:
cat RNA-Seq_geneStructure.gb | perl -ne '
  if ($_ =~ m/LOCUS\s+(\S+)\s/) {
    $txLocus = $1;
  } elsif ($_ =~ m/\/gene=\"(\S+)\"/) {
    $txInGb3{$1} = $txLocus
  }
  if(eof()) {
    foreach (keys %txInGb3) {
      print "$_\t$txInGb3{$_}\n";
    }
  }' > loci.lst

got error msg:

Unmatched '.

However I used correct quotation marks from my keyboard, not copied and pasted from pdf.

**Comment by KatharinaHoff** [comment]
The underscores are missing.

Anyway, try this script, instead: https://github.com/Gaius-Augustus/Augustus/commit/211325f797c96c3194d449a39fa51113a674dbfb
