### ISSUE TITLE
bamToWig.py needs 'import urllib'

### ISSUE THREAD

**Issue by michaelkarlcoleman** [Gaius-Augustus/Augustus#93]
The import needed to make this line work seems to be missing:

https://github.com/Gaius-Augustus/Augustus/blob/b055bc6d3859ab30db378fc82f8ddcb1ce45df72/scripts/bamToWig.py#L153

**Comment by KatharinaHoff** [comment]
Thank you for spotting this. It is fixed with commit https://github.com/Gaius-Augustus/Augustus/commit/d85cea508d29535d53adfdd81d38dace4301bd97

Katharina
