### ISSUE TITLE
Many system() errors in aa2nonred ignored

### ISSUE THREAD

**Issue by michaelkarlcoleman** [Gaius-Augustus/Augustus#97]
This script seems to be ignoring errors in `system(...)` in a number of places, rather than noticing them and failing with a diagnostic message and error status code.

This is a problem for callers like `braker.pl`, which then proceed blithely on.

https://github.com/Gaius-Augustus/Augustus/blob/61314182425283eb938a1aa8327128e53eeb194a/scripts/aa2nonred.pl#L186

**Comment by KatharinaHoff** [comment]
Thank you for reporting this.

I added a check for return code 0 of all system commands, and script will die with error message if it is not 0, commit https://github.com/Gaius-Augustus/Augustus/commit/a97998b86649e506444d4c812fa634e12b5fc376
