### ISSUE TITLE
minor: bad err delete in createAugustusJoblist

### ISSUE THREAD

**Issue by michaelkarlcoleman** [Gaius-Augustus/Augustus#98]
The sense for this `rm` is incorrect.  It deletes the error file if and only if it is non-empty.

Better something like
```
if [ ! -s $errorfilename ]; then rm -f $errorfilename; fi
```

https://github.com/Gaius-Augustus/Augustus/blob/61314182425283eb938a1aa8327128e53eeb194a/scripts/createAugustusJoblist.pl#L166-L167

**Comment by KatharinaHoff** [comment]
Thank you for spotting this!

Fixed with commit https://github.com/Gaius-Augustus/Augustus/commit/0dca4c3d3d38442d7bb08d90c8fbfd67b1d4c6d3 .

Katharina
